version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8041:8041"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8041"
    environment:
      - DB_HOST=db
      - DB_NAME=film_hobo_db
      - DB_USER=film_hobo_user
      - DB_PASS=film_hobo_pass
    depends_on:
      - db

  db:
    image: postgres:12.8-alpine
    environment:
      - POSTGRES_DB=film_hobo_db
      - POSTGRES_USER=film_hobo_user
      - POSTGRES_PASSWORD=film_hobo_pass
    ports:
      - "5444:5432"
    volumes:
    - db-volume:/var/lib/postgresql/data

  redis:
    image: redis:4.0.9-alpine
  celery:
    build:
      context: .
    command: celery -A film_hobo worker -l info
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      # - SECRET_KEY=qyi$gs%)7&cw$(y8e6at3g1%h#sk+jm7ak54dz!st3k!srca^^
      # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build:
      context: .
    command: celery -A film_hobo beat -l info
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      # - SECRET_KEY=qyi$gs%)7&cw$(y8e6at3g1%h#sk+jm7ak54dz!st3k!srca^^
      # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

volumes:
  db-volume: