# Generated by Django 3.1.7 on 2021-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='initialintrestedusers',
            options={'verbose_name': 'Initial Intrested User', 'verbose_name_plural': 'Initial Intrested Users'},
        ),
        migrations.AlterField(
            model_name='initialintrestedusers',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='initialintrestedusers',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='initialintrestedusers',
            name='designation',
            field=models.ManyToManyField(blank=True, to='initial_user.Designation', verbose_name='Designations'),
        ),
    ]
