# Generated by Django 3.1.7 on 2021-04-08 06:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('initial_user', '0002_auto_20210407_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialintrestedusers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Contact Phone Number'),
        ),
    ]
