# Generated by Django 3.1 on 2021-07-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hobo_user', '0046_auto_20210715_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('password', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobo_user.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_description', models.TextField(blank=True, null=True, verbose_name='Scene Description')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.character', verbose_name='Character')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobo_user.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Sides',
                'verbose_name_plural': 'Sides',
            },
        ),
    ]
