# Generated by Django 3.1 on 2021-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
