# Generated by Django 3.1 on 2021-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210716_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sides',
            old_name='scene_description',
            new_name='scene_1',
        ),
        migrations.AddField(
            model_name='sides',
            name='scene_2',
            field=models.TextField(blank=True, null=True, verbose_name='Scene Description'),
        ),
        migrations.AddField(
            model_name='sides',
            name='scene_3',
            field=models.TextField(blank=True, null=True, verbose_name='Scene Description'),
        ),
    ]
