# Generated by Django 3.1 on 2021-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210719_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='password',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
