# Generated by Django 3.1 on 2021-07-20 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobo_user', '0051_auto_20210720_0544'),
        ('project', '0005_auto_20210720_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('agent_name', models.CharField(blank=True, max_length=250, null=True)),
                ('agent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audition_user_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.character', verbose_name='Character')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_user_location', to='hobo_user.location', verbose_name='Location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobo_user.project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
