# Generated by Django 3.1 on 2021-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_audition'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='video_type',
            field=models.CharField(blank=True, choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook')], default='vimeo', max_length=150, null=True, verbose_name='Video Type'),
        ),
        migrations.AddField(
            model_name='audition',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
