# Generated by Django 3.1 on 2021-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210722_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo'), ('facebook', 'Facebook')], default='vimeo', max_length=150, null=True, verbose_name='Video Type'),
        ),
    ]
