# Generated by Django 3.1 on 2021-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210722_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audition',
            options={'verbose_name': 'Audition', 'verbose_name_plural': 'Audition'},
        ),
        migrations.AddField(
            model_name='audition',
            name='status',
            field=models.CharField(choices=[('attached', 'Attached'), ('passed', 'Passed'), ('applied', 'Applied'), ('callback', 'Callback')], default='applied', max_length=150, verbose_name='Status'),
        ),
    ]
