# Generated by Django 3.1 on 2021-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210722_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image size:370 X 248.', null=True, upload_to='thumbnail/'),
        ),
    ]
