# Generated by Django 3.1 on 2021-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_audition_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
