# Generated by Django 3.1 on 2021-07-28 04:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_character_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sides',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
