# Generated by Django 3.1.7 on 2021-03-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobo_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
